[package]
name = "ablate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ablate_derive = { path = "ablate_derive", version = "0.1.0" }

[workspace]